// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBixvb-hZvaq2GAVUiL5lbzsxwk27LmYlw',
    appId: '1:631249837835:web:392f6c69c8f4d3053ecc0e',
    messagingSenderId: '631249837835',
    projectId: 'flutter-intern-6575d',
    authDomain: 'flutter-intern-6575d.firebaseapp.com',
    storageBucket: 'flutter-intern-6575d.appspot.com',
    measurementId: 'G-W7SRQTX54G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp5VkQU1neXGix0U40Ow5pR0YiDgEg9Tg',
    appId: '1:631249837835:android:f23619c0b2d2cd583ecc0e',
    messagingSenderId: '631249837835',
    projectId: 'flutter-intern-6575d',
    storageBucket: 'flutter-intern-6575d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD-EsmVAOEpnHIStZLqE9356WSaCqTARI',
    appId: '1:631249837835:ios:3e3d8ddb733c086e3ecc0e',
    messagingSenderId: '631249837835',
    projectId: 'flutter-intern-6575d',
    storageBucket: 'flutter-intern-6575d.appspot.com',
    iosBundleId: 'com.example.intern',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD-EsmVAOEpnHIStZLqE9356WSaCqTARI',
    appId: '1:631249837835:ios:dff77a8fe00c4c923ecc0e',
    messagingSenderId: '631249837835',
    projectId: 'flutter-intern-6575d',
    storageBucket: 'flutter-intern-6575d.appspot.com',
    iosBundleId: 'com.example.intern.RunnerTests',
  );
}
